namespace SwashbucklerDiary.Shared
{
    public enum Setting
    {
        Language, 
        Title, 
        Markdown,
        UserName,
        Sign,
        Avatar,
        PrivacyMode, 
        PrivatePassword,
        BackupsPath,
        ThemeState,
        FirstSetLanguage,
        FirstAgree,
        WebDAVServerAddress,
        WebDAVAccount,
        WebDAVPassword,
        WelcomeText,
        Date,
        DiaryCardIcon,
        AlertTimeout,
        WebDAVCopyResources,
        DiaryCardDateFormat,
        AchievementsAlert,
        LANDeviceName,
        LANScanPort,
        LANTransmissionPort,
    }
}
