namespace SwashbucklerDiary.Shared
{
    public enum Setting
    {
        Language,
        Title,
        Markdown,
        UserName,
        Sign,
        Avatar,
        PrivacyMode,
        PrivatePassword,
        Theme,
        FirstSetLanguage,
        FirstAgree,
        WebDavConfig,
        WelcomeText,
        IndexDate,
        DiaryCardIcon,
        AlertTimeout,
        WebDAVCopyResources,
        DiaryCardDateFormat,
        AchievementsAlert,
        LANDeviceName,
        LANScanPort,
        LANTransmissionPort,
        StatisticsCard,
        EditAutoSave,
        DiarySort,
        TagSort,
        LocationSort,
        UpdateNotPrompt
    }
}
